### ISSUE TITLE
Version 2.0.0 tracking

### ISSUE THREAD

**Issue by krisprice** [krisprice/ipnet#9]
Version 2.0.0 tracking items:

- [x] Replace Emu128 with Rust native u128 when stable
- [x] Remove the `with-serde` feature name, see https://github.com/krisprice/ipnet/pull/8
- [x] Inherit the `Contains::contains()` methods in the types so that it's not necessary to use the `Contains` trait to access these methods.
- [x] Remove the `Deref` to the contained IP address
- [ ] Implement relevant methods that were previously `Deref`'d directly on the IP network types, and make them correct for networks, e.g. `172.16.0.0/8` would previously return `true` using call to `is_private()` on the contained IP address, but technically it is not as it's larger than the `172.16.0.0/12` private space.
- [ ] Run through the different comparisons (Eq, Ord, PartialOrd) and make sure they make sense and are working as would be expected.
